from __future__ import annotations

DEFAULT_ANALYTICS_DAYS = 7
MAX_ANALYTICS_DAYS = 90
DEFAULT_FETCH_LIMIT = 500
MAX_FETCH_LIMIT = 1000
DEFAULT_EXTENDED_LIMIT = 1000
MAX_EXTENDED_LIMIT = 2000
DEFAULT_SYNC_RUN_LIMIT = 50
MAX_SYNC_RUN_LIMIT = 200
DEFAULT_APPROVAL_LOOKBACK_DAYS = 30
MAX_APPROVAL_LOOKBACK_DAYS = 180
MAX_QUERY_TEXT_LENGTH = 120
MAX_OWNER_NAME_LENGTH = 120
