create extension if not exists vector;

create table if not exists site_metrics (
  metric_key text primary key,
  metric_value bigint not null default 0,
  updated_at timestamptz not null default now()
);

insert into site_metrics (metric_key, metric_value)
values ('page_views_total', 0)
on conflict (metric_key) do nothing;

insert into site_metrics (metric_key, metric_value)
values ('unique_visitors_total', 0)
on conflict (metric_key) do nothing;

create table if not exists site_visitors (
  visitor_id text primary key,
  visit_count bigint not null default 1,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists chat_logs (
  id bigint generated by default as identity primary key,
  session_id text not null,
  intent_name text,
  intent_lane text,
  preferred_answer_intent text,
  source text,
  job_number text,
  user_message text,
  bot_reply text,
  created_at timestamptz not null default now()
);

create or replace function increment_site_metric(
  metric_name text,
  delta bigint default 1
)
returns table (
  metric_key text,
  metric_value bigint
)
language plpgsql
as $$
begin
  insert into site_metrics (metric_key, metric_value, updated_at)
  values (metric_name, delta, now())
  on conflict (metric_key)
  do update set
    metric_value = site_metrics.metric_value + excluded.metric_value,
    updated_at = now();

  return query
  select site_metrics.metric_key, site_metrics.metric_value
  from site_metrics
  where site_metrics.metric_key = metric_name;
end;
$$;

create table if not exists knowledge_base (
  id text primary key,
  topic text not null,
  question text,
  answer text,
  keywords text,
  intent text,
  content text,
  embedding vector(768),
  updated_at timestamptz default now()
);

alter table knowledge_base
  add column if not exists keywords text;

alter table knowledge_base
  add column if not exists intent text;

create index if not exists knowledge_base_embedding_idx
  on knowledge_base
  using ivfflat (embedding vector_cosine_ops)
  with (lists = 100);

create or replace function match_knowledge(
  query_embedding vector(768),
  match_count int,
  match_threshold float
)
returns table (
  id text,
  topic text,
  question text,
  answer text,
  intent text,
  similarity float
)
language sql
stable
as $$
  select
    id,
    topic,
    question,
    answer,
    intent,
    1 - (embedding <=> query_embedding) as similarity
  from knowledge_base
  where 1 - (embedding <=> query_embedding) > match_threshold
  order by similarity desc
  limit match_count;
$$;
