create table if not exists tracking_resolution_queue (
  id bigint generated by default as identity primary key,
  job_number text not null,
  user_message text,
  session_id text,
  status text not null default 'pending',
  source text,
  resolved_carrier text,
  resolution_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists tracking_resolution_queue_job_number_idx
  on tracking_resolution_queue (job_number);

create index if not exists tracking_resolution_queue_status_idx
  on tracking_resolution_queue (status);

create index if not exists tracking_resolution_queue_created_at_idx
  on tracking_resolution_queue (created_at desc);
