name: Docker Validate

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t frieght-backend:ci .
